ros_ovpn_srv_port: '1194'
ros_ovpn_srv_profile: OVPN-Server
ros_ovpn_srv_vpn_subnet: 10.253.0.0/24
ros_ovpn_srv_certificate: OVPN_Server
ros_ovpn_srv_certificate: "{{ certificates[1]['ros_cert_name'] }}"

#ros_ovpn_srv_clients: "{{ vault_ros_ovpn_srv_clients }}"
ros_ovpn_srv_clients:
  Bjoern:
    name: Bjoern
    password: "{{ vault_client1_pwd }}"
    address: 10.253.0.1
    # route which will be client.ovpn file. Which networks will routes from client via tunnel
    route: 10.4.5.0/24
    allowed_networks:
      - 10.4.5.78-10.4.5.122
  Stefan:
    name: Stefan
    password: "{{ vault_client2_pwd }}"
    address: 10.253.0.2
    route: 10.0.0.0/9
    allowed_networks:
      - 10.4.3.5-10.4.3.59
      - 10.4.5.5-10.4.5.65
      - 10.70.44.19
      - 10.70.44.30
      - 10.70.44.32-10.70.44.35
      - 10.70.44.37-10.70.44.38
      - 10.70.44.44-10.70.44.47
      - 10.5.0.0-10.5.0.255
      - 10.5.9.0-10.5.9.255
  Marco:
    name: Marco
    password: "{{ vault_client3_pwd }}"
    address: 10.253.0.3
    # route which will be client.ovpn file. Which networks will routes from client via tunnel
    route: 10.4.2.0/23
    allowed_networks:
      - 10.4.2.110-10.4.2.156
      - 10.4.3.145-10.4.3.184
  Operator1:
    name: Operator1
    password: "{{ vault_client4_pwd }}"
    address: 10.253.0.4
    # route which will be client.ovpn file. Which networks will routes from client via tunnel
    route: 10.0.0.0/8
    allowed_networks:
      - 10.3.0.1
      - 10.4.0.1
      - 10.5.0.1
      - 10.6.0.1
      - 10.0.0.4
  Operator2:
    name: Operator2
    password: "{{ vault_client5_pwd }}"
    address: 10.253.0.5
    # route which will be client.ovpn file. Which networks will routes from client via tunnel
    route: 10.0.0.0/8
    allowed_networks:
      - 10.3.0.1
      - 10.4.0.1
      - 10.5.0.1
      - 10.6.0.1
      - 10.0.0.4
  Operator3:
    name: Operator3
    password: "{{ vault_client6_pwd }}"
    address: 10.253.0.6
    # route which will be client.ovpn file. Which networks will routes from client via tunnel
    route: 10.0.0.0/8
    allowed_networks:
      - 10.3.0.1
      - 10.4.0.1
      - 10.5.0.1
      - 10.6.0.1
      - 10.0.0.4
  Maxim:
    name: Maxim
    password: "{{ vault_client7_pwd }}"
    address: 10.253.0.7
    # route which will be client.ovpn file. Which networks will routes from client via tunnel
    route: 10.0.0.0/8
    allowed_networks:
      - 0.0.0.0/0
  Andrew:
    name: Andrew
    password: "{{ vault_client8_pwd }}"
    address: 10.253.0.8
    # route which will be client.ovpn file. Which networks will routes from client via tunnel
    route: 10.0.0.0/8
    allowed_networks:
      - 0.0.0.0/0
  Martin:
    name: Martin
    password: "{{ vault_client9_pwd }}"
    address: 10.253.0.2
    route: 10.0.0.0/9
    allowed_networks:
      - 10.4.3.5-10.4.3.59
      - 10.4.5.5-10.4.5.65
      - 10.70.44.19
      - 10.70.44.30
      - 10.70.44.32-10.70.44.35
      - 10.70.44.37-10.70.44.38
      - 10.70.44.44-10.70.44.47
      - 10.5.0.0-10.5.0.255
      - 10.5.9.0-10.5.9.255
  Igor:
    name: Igor
    password: "{{ vault_client10_pwd }}"
    address: 10.253.0.10
    # route which will be client.ovpn file. Which networks will routes from client via tunnel
    route: 10.0.0.0/8
    allowed_networks:
      - 0.0.0.0/0

client_certs:
  - ros_cert_name: Bjoern
    ros_cert_days_valid: 365
    ros_cert_key_size: 4096
    ros_cert_key_usage: "tls-client"
    ros_cert_ca_name: CA
    ros_cert_is_ca: false
  - ros_cert_name: Stefan
    ros_cert_days_valid: 365
    ros_cert_key_size: 4096
    ros_cert_key_usage: "tls-client"
    ros_cert_ca_name: CA
    ros_cert_is_ca: false
  - ros_cert_name: Marco
    ros_cert_days_valid: 365
    ros_cert_key_size: 4096
    ros_cert_key_usage: "tls-client"
    ros_cert_ca_name: CA
    ros_cert_is_ca: false
  - ros_cert_name: Operator1
    ros_cert_days_valid: 3650
    ros_cert_key_size: 4096
    ros_cert_key_usage: "tls-client"
    ros_cert_ca_name: CA
    ros_cert_is_ca: false
  - ros_cert_name: Operator2
    ros_cert_days_valid: 3650
    ros_cert_key_size: 4096
    ros_cert_key_usage: "tls-client"
    ros_cert_ca_name: CA
    ros_cert_is_ca: false
  - ros_cert_name: Operator3
    ros_cert_days_valid: 3650
    ros_cert_key_size: 4096
    ros_cert_key_usage: "tls-client"
    ros_cert_ca_name: CA
    ros_cert_is_ca: false
  - ros_cert_name: Maxim
    ros_cert_days_valid: 3650
    ros_cert_key_size: 4096
    ros_cert_key_usage: "tls-client"
    ros_cert_ca_name: CA
    ros_cert_is_ca: false
  - ros_cert_name: Andrew
    ros_cert_days_valid: 3650
    ros_cert_key_size: 4096
    ros_cert_key_usage: "tls-client"
    ros_cert_ca_name: CA
    ros_cert_is_ca: false
  - ros_cert_name: Martin
    ros_cert_days_valid: 365
    ros_cert_key_size: 4096
    ros_cert_key_usage: "tls-client"
    ros_cert_ca_name: CA
    ros_cert_is_ca: false
  - ros_cert_name: Igor
    ros_cert_days_valid: 3650
    ros_cert_key_size: 4096
    ros_cert_key_usage: "tls-client"
    ros_cert_ca_name: CA
    ros_cert_is_ca: false

certificates:
  - ros_cert_name: CA
    ros_cert_days_valid: 3650
    ros_cert_key_size: 4096
    ros_cert_key_usage: "crl-sign,key-cert-sign"
    ros_cert_is_ca: true
  - ros_cert_name: OVPN_Server
    ros_cert_days_valid: 3650
    ros_cert_key_size: 4096
    ros_cert_key_usage: "digital-signature,key-encipherment,tls-server"
    ros_cert_ca_name: CA
    ros_cert_is_ca: false