ros_cert_CA_name: CA
ros_cert_CA_days_valid: 3650
ros_cert_CA_key_size: 4096

ros_cert_name: cert
ros_cert_days_valid: 3650
ros_cert_key_size: 4096
ros_cert_key_usage: "digital-signature,key-encipherment,tls-server" #for OVPN Server