- name: generate rsc
  template:
    src: l2tp-server.rsc.j2
    dest: /tmp/{{ inventory_hostname }}-l2tp-server.rsc

- name: copy rsc to router
  command: scp -P {{ ansible_ssh_port }} /tmp/{{ inventory_hostname }}-l2tp-server.rsc {{ansible_ssh_user}}@{{ansible_host}}:l2tp-server.rsc

- name: run rsc
  routeros_command:
    commands: "/import file=l2tp-server.rsc"
  register: system_print

- name: debug print
  debug:
    var: system_print.stdout_lines
