- name: generate rsc
  template:
    src: ovpn-server.rsc.j2
    dest: /tmp/{{ inventory_hostname }}-ovpn-server.rsc

- name: copy rsc to router
  command: scp -P {{ ansible_ssh_port }} /tmp/{{ inventory_hostname }}-ovpn-server.rsc {{ansible_ssh_user}}@{{ansible_host}}:ovpn-server.rsc

- name: run rsc
  routeros_command:
    commands: 
      - "/import file=ovpn-server.rsc"
      - "file remove ovpn-server.rsc"
  register: system_print

- name: debug print
  debug:
    var: system_print.stdout_lines

- name: clean
  file:
    path: /tmp/{{ inventory_hostname }}-ovpn-server.rsc
    state: absent
