---

- name: create alertmanager_bot system group
  group:
    name: "{{ alertmanager_bot_group }}"
    system: true
    state: present

- name: create alertmanager_bot system user
  user:
    name: "{{ alertmanager_bot_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ alertmanager_bot_group }}"
    home: "{{ alertmanager_bot_root_dir }}"
    createhome: false

- name: create alertmanager_bot directories
  file:
    path: "{{ alertmanager_bot_root_dir }}"
    state: directory
    owner: "{{ alertmanager_bot_user }}"
    group: "{{ alertmanager_bot_group }}"
    mode: 0750

- name: initialize the deploy root and gather facts
  deploy_helper:
    path: "{{ alertmanager_bot_root_dir }}"
    release: "{{ alertmanager_bot_version }}"
    shared_path: "{{ alertmanager_bot_shared_dir }}"
    state: present

- name: create release directory
  file:
    dest: "{{ deploy_helper.new_release_path }}"
    state: directory
    owner: "{{ alertmanager_bot_user }}"
    group: "{{ alertmanager_bot_group }}"
    mode: 0750

- name: download release
  get_url:
    url: "{{ alertmanager_bot_download_url }}"
    dest: "{{ deploy_helper.new_release_path }}/alertmanager_bot"
    remote_src: true
  environment:
    " {{ proxy_env }} "
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2

- name: copy message template
  copy:
    src: "{{ alertmanager_bot_default_template_file }}"
    dest: "{{ deploy_helper.new_release_path }}/default.tmpl"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart alertmanager bot

- name: set permissions for executable file
  file:
    dest: "{{ deploy_helper.new_release_path }}/alertmanager_bot"
    state: file
    owner: "{{ alertmanager_bot_user }}"
    group: "{{ alertmanager_bot_group }}"
    mode: 0750

- name: set permissions for shared directory
  file:
    dest: "{{ deploy_helper.shared_path }}"
    state: directory
    owner: "{{ alertmanager_bot_user }}"
    group: "{{ alertmanager_bot_group }}"
    mode: 0750
    recurse: true

- name: create systemd service unit
  template:
    src: alertmanager_bot.service.j2
    dest: /etc/systemd/system/alertmanager_bot.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart alertmanager bot

- name: finalize the deploy, removing the unfinished file and switching the symlink
  deploy_helper:
    path: "{{ alertmanager_bot_root_dir }}"
    release: "{{ deploy_helper.new_release }}"
    state: finalize
  notify:
    - restart alertmanager bot
